cmake –G Ninja ../llvm \
-DCMAKE_CXX_STANDARD=17 \
-DCMAKE_C_COMPILER=gcc \
-DCMAKE_CXX_COMPILER=g++ \
-DCMAKE_BUILD_TYPE=Debug \
-DCMAKE_INSTALL_PREFIX="~/tools/llvm_backend_test" \
-DLLVM_ENABLE_RTTI=ON \
-DLLVM_ENABLE_ASSERTIONS=ON \
-DLLVM_BUILD_LLVM_DYLIB=ON \
-DLLVM_DYLIB_COMPONENTS="all" \
-DLLVM_ENABLE_PROJECTS="clang" \
-DLLVM_TARGETS_TO_BUILD="RISCV" \
-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="IMCE" \
-DLLVM_ENABLE_DOXYGEN=On \
-DLLVM_CCACHE_BUILD="true"

# -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="IMCE"
# -DLLVM_TARGETS_TO_BUILD="RISCV;X86;Mips"
# -DLLVM_DYLIB_COMPONENTS="all"
# -DLLVM_ENABLE_PROJECTS="clang"
# -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="M88k;IMCE"
# -DLLVM_ENABLE_PROJECTS="clang;mlir"
# -DLLVM_TARGETS_TO_BUILD=""
# -DCMAKE_C_FLAGS="-pg"
# -DCMAKE_CXX_FLAGS="-pg"
#-DLLVM_TARGETS_TO_BUILD="all"
